import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getPreviewUrl, loginWithSpotify } from '../utils/spotify'

export default function Home() {

  const play = async () => {
    const url = await getPreviewUrl('spotify:track:2vRI17zbIpXatNS3IS1ktx')
    const audio = new Audio(url)
    audio.play()
  }

  const login = async () => {
    loginWithSpotify(window.location.origin + '/callback')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={login}>
          Login with Spotify
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
